### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by univeous** [ninetailsrabbit/match3-board#1]
I took a quick look at the repo and I think it's great!

It just lacks documentation so it may not be very understandable.

This is definitely not a rant, but do you plan on adding some documentation at some point?

Cheers!

**Comment by ninetailsrabbit** [comment]
Hi @univeous, thank you for paying attention to the repository. The node is functional and I used it for a game I never published.

Sorry for not having the documentation, I'm looking for a way to make it easy to understand and I probably have to add some video resource to bring out the full potential but I didn't want to wait for this to happen so that someone could use it by looking at the source code..

In the next week I will probably start with the basic documentation and add some example scene with a funcional board that uses normal, special, obstacle and custom pieces.

- - - 
The workflow basically it's:
- Add the node to the desired scene
- Create the piece definitions using the PieceDefinitionResource
- Define the exported parameters of this node (grid size, swap mode, maximum movements, etc)
- Extend the base PieceAnimator class to create your own animations
- Extend the base SequenceConsumer class to decide how your game will behave when a sequence is consumed by the player
- Connect to the Match3Board signals and reacting to them to take one path or another

Now writing this looks more complex than I thought, I will get to work as soon as I can on the documentation.
