### ISSUE TITLE
Add more example pieces

### ISSUE THREAD

**Issue by univeous** [ninetailsrabbit/match3-board#3]
**Is your feature request related to a problem? Please describe.**
It is not particularly easy to figure out how to implement some specific logic. For example, I want to implement a shape bomb (when swapping with any piece, match all pieces of the same shape), but I'm not sure what the best practice is to use this plugin to achieve this.
**Describe the solution you'd like**
I hope to add more example pieces to demonstrate some common use cases, such as shape bombs, row bombs and column bombs.

**Describe alternatives you've considered**
Users to implement this on their own?  I'm sure I could do this with some logic, I'm just not sure if it's the best/logical fit for this repository.

**Additional context**
This may also be related to #1. In addition, I'm sorry that I raised so many issues. I just think this project is very good, and I hope it can develop better:)

**Comment by ninetailsrabbit** [comment]
Hi @univeous I was just dropping by to let you know that I have released a new version.

There is more documentation but it is still in process. I have added a demo scene so you can see how you can create a board and even add special pieces.

I hope to improve it over time to make it more enjoyable for the end user because in this refactor I have solved many bugs that existed when the board consumed many pieces in a short space of time.

Now it is much easier to add pieces with 100% customizable behavior.
